# mongodb connection string for the main database
mongo="mongodb://df63c08fb28057986684ec3c3a07b61c:49b50e178c579b5cc3c47d687e8eb101@leader.mongodb.discoverd:27017/fb605848d712d23e9f339a1746063866"

# redis connection string to connect to a single master (see below for Sentinel example)
redis="redis://:89100a9128e613ae0c94@leader.redis-a2c583b3-8a1c-4fe2-81fb-029293a769a5.discoverd:6379"

# WildDuck allows using different kind of data in different databases
# If you do not provide a database config value, then main database connection
# is used for everything
# You can either use a database name (uses shared connection) or a configutaion
# url (creates a separate connection) for each databases

# Optional database name or connection url for GridFS if you do not want to
# use the main db for storing attachments. Useful if you want
# to use a different mount folder or storage engine
#gridfs="wildduck"

# Optional database name or connection url for users collection if you do not want to
# use the main db for storing user/address data. Useful if you want
# to use a different mount folder or storage engine
#users="wildduck"

# Optional database name or connection url for ZoneMTA queue database. This is
# used to push outbound emails to the sending queue
sender="zone-mta"

#queued="mail"

[redis]
host="leader.redis-a2c583b3-8a1c-4fe2-81fb-029293a769a5.discoverd"
port=6379
db=3

## Connect to Redis Sentinel instead of single master
# [redis]
# name="mymaster"
# password=""
# db=3
# [[redis.sentinels]]
#   host="54.36.85.113"
#   port=26379
# [[redis.sentinels]]
#   host="54.36.85.114"
#   port=26379
# [[redis.sentinels]]
#   host="54.36.85.115"
#   port=26379
